ALTER TABLE SKILL_AUTH
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_SKILL_AUTH
		CASCADE;

ALTER TABLE COMMON_CODE
	DROP
		CONSTRAINT FK_COMMON_CODE_GROUP_TO_COMMON_CODE
		CASCADE;

ALTER TABLE ATTATCH_FILE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_ATTATCH_FILE
		CASCADE;

ALTER TABLE DCLZ_TYPE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_DCLZ_TYPE
		CASCADE;

ALTER TABLE VACATION
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_VACATION
		CASCADE;

ALTER TABLE ATRZ
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ
		CASCADE;

ALTER TABLE ATRZ
	DROP
		CONSTRAINT FK_DOC_FORM_TO_ATRZ
		CASCADE;

ALTER TABLE ATRZ_LINE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_LINE
		CASCADE;

ALTER TABLE ATRZ_LINE
	DROP
		CONSTRAINT FK_ATRZ_TO_ATRZ_LINE
		CASCADE;

ALTER TABLE VACTION_PLAN
	DROP
		CONSTRAINT FK_ATRZ_TO_VACTION_PLAN
		CASCADE;

ALTER TABLE ATRZ_LIKE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_LIKE
		CASCADE;

ALTER TABLE ATRZ_EMP
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_EMP
		CASCADE;

ALTER TABLE ATRZ_EMP
	DROP
		CONSTRAINT FK_ATRZ_LIKE_TO_ATRZ_EMP
		CASCADE;

ALTER TABLE SCHEDULE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_SCHEDULE
		CASCADE;

ALTER TABLE SCHEDULE
	DROP
		CONSTRAINT FK_SCHEDULE_LABEL_COLOR_TO_SCHEDULE
		CASCADE;

ALTER TABLE SCHEDULE_AUTH_GROUP
	DROP
		CONSTRAINT FK_SCHEDULE_TO_SCHEDULE_AUTH_GROUP
		CASCADE;

ALTER TABLE SCHEDULE_AUTH_GROUP
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_SCHEDULE_AUTH_GROUP
		CASCADE;

ALTER TABLE SCHEDULE_TYPE
	DROP
		CONSTRAINT FK_SCHEDULE_TO_SCHEDULE_TYPE
		CASCADE;

ALTER TABLE MAIL
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_MAIL
		CASCADE;

ALTER TABLE MAIL
	DROP
		CONSTRAINT FK_MAIL_LABEL_TO_MAIL
		CASCADE;

ALTER TABLE MAIL_LABEL
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_MAIL_LABEL
		CASCADE;

ALTER TABLE MAIL_TEMPLATE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_MAIL_TEMPLATE
		CASCADE;

ALTER TABLE PROJECT
	DROP
		CONSTRAINT FK_PROJECT_CATEGORY_TO_PROJECT
		CASCADE;

ALTER TABLE PROJECT_EMP
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_PROJECT_EMP
		CASCADE;

ALTER TABLE PROJECT_EMP
	DROP
		CONSTRAINT FK_PROJECT_TO_PROJECT_EMP
		CASCADE;

ALTER TABLE PROJECT_EMP
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_PROJECT_EMP2
		CASCADE;

ALTER TABLE PROJECT_TASK
	DROP
		CONSTRAINT FK_PROJECT_TASK_TO_PROJECT_TASK
		CASCADE;

ALTER TABLE PROJECT_TASK
	DROP
		CONSTRAINT FK_PROJECT_EMP_TO_PROJECT_TASK
		CASCADE;

ALTER TABLE BBS
	DROP
		CONSTRAINT FK_BBS_CTGRY_TO_BBS
		CASCADE;

ALTER TABLE BBS
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_BBS
		CASCADE;

ALTER TABLE BBS_ANSWER
	DROP
		CONSTRAINT FK_BBS_TO_BBS_ANSWER
		CASCADE;

ALTER TABLE BBS_ANSWER
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_BBS_ANSWER
		CASCADE;

ALTER TABLE BBS_LIKE
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_BBS_LIKE
		CASCADE;

ALTER TABLE BBS_LIKE
	DROP
		CONSTRAINT FK_BBS_TO_BBS_LIKE
		CASCADE;

ALTER TABLE CHAT_EMP
	DROP
		CONSTRAINT FK_CHAT_ROOM_TO_CHAT_EMP
		CASCADE;

ALTER TABLE CHAT_EMP
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_CHAT_EMP
		CASCADE;

ALTER TABLE CHAT_MESSAGE
	DROP
		CONSTRAINT FK_CHAT_EMP_TO_CHAT_MESSAGE
		CASCADE;

ALTER TABLE NOTIFICATION
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_NOTIFICATION
		CASCADE;

ALTER TABLE FOLDER_FILE
	DROP
		CONSTRAINT FK_FOLDER_TO_FOLDER_FILE
		CASCADE;

ALTER TABLE TASK_LINK
	DROP
		CONSTRAINT FK_PROJECT_TASK_TO_TASK_LINK
		CASCADE;

ALTER TABLE TASK_ANSERT
	DROP
		CONSTRAINT FK_PROJECT_TASK_TO_TASK_ANSERT
		CASCADE;

ALTER TABLE TASK_ANSERT
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_TASK_ANSERT
		CASCADE;

ALTER TABLE PAY_REQUEST
	DROP
		CONSTRAINT FK_PRQUDO_TO_PAY_REQUEST
		CASCADE;

ALTER TABLE PAY_CONFIRM
	DROP
		CONSTRAINT FK_PAY_REQUEST_TO_PAY_CONFIRM
		CASCADE;

ALTER TABLE NOTIFICATION_SETTING
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_NOTIFICATION_SETTING
		CASCADE;

ALTER TABLE AUTH
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_AUTH
		CASCADE;

ALTER TABLE VACATION_ADJU
	DROP
		CONSTRAINT FK_EMPLOYEE_TO_VACATION_ADJU
		CASCADE;

ALTER TABLE EMPLOYEE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SKILL_AUTH
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE COMMON_CODE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ATTATCH_FILE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE DCLZ_TYPE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE VACATION
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ATRZ
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ATRZ_LINE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE DOC_FORM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE VACTION_PLAN
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ATRZ_LIKE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE ATRZ_EMP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SCHEDULE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SCHEDULE_AUTH_GROUP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SCHEDULE_TYPE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MAIL
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MAIL_LABEL
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE MAIL_TEMPLATE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PROJECT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PROJECT_EMP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PROJECT_TASK
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BBS
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BBS_CTGRY
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BBS_ANSWER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE BBS_LIKE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE CHAT_ROOM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE CHAT_EMP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE CHAT_MESSAGE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE NOTIFICATION
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE FOLDER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE FOLDER_FILE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE COMMON_CODE_GROUP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE TASK_LINK
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PROJECT_CATEGORY
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE TASK_ANSERT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PRQUDO
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PAY_REQUEST
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE PAY_CONFIRM
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE SCHEDULE_LABEL_COLOR
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE NOTIFICATION_SETTING
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE AUTH
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

ALTER TABLE VACATION_ADJU
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_EMPLOYEE;

DROP INDEX PK_SKILL_AUTH;

DROP INDEX PK_COMMON_CODE;

DROP INDEX PK_ATTATCH_FILE;

DROP INDEX PK_DCLZ_TYPE;

DROP INDEX PK_VACATION;

DROP INDEX PK_ATRZ;

DROP INDEX PK_ATRZ_LINE;

DROP INDEX PK_DOC_FORM;

DROP INDEX PK_VACTION_PLAN;

DROP INDEX PK_ATRZ_LIKE;

DROP INDEX PK_ATRZ_EMP;

DROP INDEX PK_SCHEDULE;

DROP INDEX PK_SCHEDULE_AUTH_GROUP;

DROP INDEX PK_SCHEDULE_TYPE;

DROP INDEX PK_MAIL;

DROP INDEX PK_MAIL_LABEL;

DROP INDEX PK_MAIL_TEMPLATE;

DROP INDEX PK_PROJECT;

DROP INDEX PK_PROJECT_EMP;

DROP INDEX PK_PROJECT_TASK;

DROP INDEX PK_BBS;

DROP INDEX PK_BBS_CTGRY;

DROP INDEX PK_BBS_ANSWER;

DROP INDEX PK_BBS_LIKE;

DROP INDEX PK_CHAT_ROOM;

DROP INDEX PK_CHAT_EMP;

DROP INDEX PK_CHAT_MESSAGE;

DROP INDEX PK_NOTIFICATION;

DROP INDEX PK_FOLDER;

DROP INDEX PK_FOLDER_FILE;

DROP INDEX PK_COMMON_CODE_GROUP;

DROP INDEX PK_TASK_LINK;

DROP INDEX PK_PROJECT_CATEGORY;

DROP INDEX PK_TASK_ANSERT;

DROP INDEX PK_PRQUDO;

DROP INDEX PK_PAY_REQUEST;

DROP INDEX PK_PAY_CONFIRM;

DROP INDEX PK_SCHEDULE_LABEL_COLOR;

DROP INDEX PK_NOTIFICATION_SETTING;

DROP INDEX PK_AUTH;

DROP INDEX PK_VACATION_ADJU;

DROP TABLE EMPLOYEE 
	CASCADE CONSTRAINTS;

DROP TABLE SKILL_AUTH 
	CASCADE CONSTRAINTS;

DROP TABLE COMMON_CODE 
	CASCADE CONSTRAINTS;

DROP TABLE ATTATCH_FILE 
	CASCADE CONSTRAINTS;

DROP TABLE DCLZ_TYPE 
	CASCADE CONSTRAINTS;

DROP TABLE VACATION 
	CASCADE CONSTRAINTS;

DROP TABLE ATRZ 
	CASCADE CONSTRAINTS;

DROP TABLE ATRZ_LINE 
	CASCADE CONSTRAINTS;

DROP TABLE DOC_FORM 
	CASCADE CONSTRAINTS;

DROP TABLE VACTION_PLAN 
	CASCADE CONSTRAINTS;

DROP TABLE ATRZ_LIKE 
	CASCADE CONSTRAINTS;

DROP TABLE ATRZ_EMP 
	CASCADE CONSTRAINTS;

DROP TABLE SCHEDULE 
	CASCADE CONSTRAINTS;

DROP TABLE SCHEDULE_AUTH_GROUP 
	CASCADE CONSTRAINTS;

DROP TABLE SCHEDULE_TYPE 
	CASCADE CONSTRAINTS;

DROP TABLE MAIL 
	CASCADE CONSTRAINTS;

DROP TABLE MAIL_LABEL 
	CASCADE CONSTRAINTS;

DROP TABLE MAIL_TEMPLATE 
	CASCADE CONSTRAINTS;

DROP TABLE PROJECT 
	CASCADE CONSTRAINTS;

DROP TABLE PROJECT_EMP 
	CASCADE CONSTRAINTS;

DROP TABLE PROJECT_TASK 
	CASCADE CONSTRAINTS;

DROP TABLE BBS 
	CASCADE CONSTRAINTS;

DROP TABLE BBS_CTGRY 
	CASCADE CONSTRAINTS;

DROP TABLE BBS_ANSWER 
	CASCADE CONSTRAINTS;

DROP TABLE BBS_LIKE 
	CASCADE CONSTRAINTS;

DROP TABLE CHAT_ROOM 
	CASCADE CONSTRAINTS;

DROP TABLE CHAT_EMP 
	CASCADE CONSTRAINTS;

DROP TABLE CHAT_MESSAGE 
	CASCADE CONSTRAINTS;

DROP TABLE NOTIFICATION 
	CASCADE CONSTRAINTS;

DROP TABLE FOLDER 
	CASCADE CONSTRAINTS;

DROP TABLE FOLDER_FILE 
	CASCADE CONSTRAINTS;

DROP TABLE COMMON_CODE_GROUP 
	CASCADE CONSTRAINTS;

DROP TABLE TASK_LINK 
	CASCADE CONSTRAINTS;

DROP TABLE PROJECT_CATEGORY 
	CASCADE CONSTRAINTS;

DROP TABLE TASK_ANSERT 
	CASCADE CONSTRAINTS;

DROP TABLE PRQUDO 
	CASCADE CONSTRAINTS;

DROP TABLE PAY_REQUEST 
	CASCADE CONSTRAINTS;

DROP TABLE PAY_CONFIRM 
	CASCADE CONSTRAINTS;

DROP TABLE SCHEDULE_LABEL_COLOR 
	CASCADE CONSTRAINTS;

DROP TABLE NOTIFICATION_SETTING 
	CASCADE CONSTRAINTS;

DROP TABLE AUTH 
	CASCADE CONSTRAINTS;

DROP TABLE VACATION_ADJU 
	CASCADE CONSTRAINTS;

CREATE TABLE EMPLOYEE (
	EMPL_NO VARCHAR2(8) NOT NULL,
	PASSWORD VARCHAR2(300) NOT NULL,
	ENABLED VARCHAR2(1) DEFAULT '1',
	EMPL_NM VARCHAR2(100) NOT NULL,
	BRTHDY VARCHAR2(8) NOT NULL,
	TELNO VARCHAR2(11) NOT NULL,
	ACNUTNO VARCHAR2(50) NOT NULL,
	BANK_NM VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	POST_NO VARCHAR2(50),
	ADRES VARCHAR2(1000),
	DETAIL_ADRES VARCHAR2(500),
	ECNY_DATE VARCHAR2(8) NOT NULL,
	RETIRE_DATE VARCHAR2(8),
	ATCH_FILE_NO NUMBER,
	ELCTRN_SIGN_IMAGE_URL VARCHAR2(2000),
	PROFL_PHOTO_URL VARCHAR2(100),
	DEPT_CODE VARCHAR2(2),
	CLSF_CODE VARCHAR2(2),
	GENDER_CODE VARCHAR2(2),
	EMPL_STTUS_CODE VARCHAR2(2),
	ANSLRY NUMBER NOT NULL,
	PARTCLR_MATTER VARCHAR2(1000),
	CONTD_EMPNO VARCHAR2(8)
);

COMMENT ON TABLE EMPLOYEE IS '사원';

COMMENT ON COLUMN EMPLOYEE.EMPL_NO IS '사원 넘버 ex) 20250001 - 아이디로 사용';

COMMENT ON COLUMN EMPLOYEE.PASSWORD IS '비밀번호 암호화';

COMMENT ON COLUMN EMPLOYEE.ENABLED IS '사용여부';

COMMENT ON COLUMN EMPLOYEE.EMPL_NM IS '사원 이름';

COMMENT ON COLUMN EMPLOYEE.BRTHDY IS '생년월일';

COMMENT ON COLUMN EMPLOYEE.TELNO IS '01000000000';

COMMENT ON COLUMN EMPLOYEE.ACNUTNO IS '계좌번호';

COMMENT ON COLUMN EMPLOYEE.BANK_NM IS '은행명';

COMMENT ON COLUMN EMPLOYEE.EMAIL IS '이메일';

COMMENT ON COLUMN EMPLOYEE.POST_NO IS '우편 번호';

COMMENT ON COLUMN EMPLOYEE.ADRES IS '주소';

COMMENT ON COLUMN EMPLOYEE.DETAIL_ADRES IS '상세 주소';

COMMENT ON COLUMN EMPLOYEE.ECNY_DATE IS '20250101';

COMMENT ON COLUMN EMPLOYEE.RETIRE_DATE IS '퇴사 일자가 있으면 퇴사한 사람임';

COMMENT ON COLUMN EMPLOYEE.ATCH_FILE_NO IS '프로필 이미지';

COMMENT ON COLUMN EMPLOYEE.ELCTRN_SIGN_IMAGE_URL IS 'base64로 저장';

COMMENT ON COLUMN EMPLOYEE.PROFL_PHOTO_URL IS '이미지 경로로 변경';

COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS 'DEPEARTMENT';

COMMENT ON COLUMN EMPLOYEE.CLSF_CODE IS 'POSITION';

COMMENT ON COLUMN EMPLOYEE.GENDER_CODE IS 'GENDER';

COMMENT ON COLUMN EMPLOYEE.EMPL_STTUS_CODE IS 'EMPL_STATUS';

COMMENT ON COLUMN EMPLOYEE.ANSLRY IS '연봉 정보가지고 급여 명세서 작업 ';

COMMENT ON COLUMN EMPLOYEE.PARTCLR_MATTER IS '인사팀 및 직장 상사만 확인 가능';

COMMENT ON COLUMN EMPLOYEE.CONTD_EMPNO IS '부재시 대결 해주는 사원 번호';

CREATE UNIQUE INDEX PK_EMPLOYEE
	ON EMPLOYEE (
		EMPL_NO ASC
	);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT PK_EMPLOYEE
		PRIMARY KEY (
			EMPL_NO
		);

CREATE TABLE SKILL_AUTH (
	EMPL_NO VARCHAR2(8) NOT NULL,
	SKLL_CODE VARCHAR2(2) NOT NULL,
	SKLL_AUTHOR_CODE VARCHAR2(30) NOT NULL
);

COMMENT ON TABLE SKILL_AUTH IS '기능 권한';

COMMENT ON COLUMN SKILL_AUTH.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN SKILL_AUTH.SKLL_CODE IS '기능 명';

COMMENT ON COLUMN SKILL_AUTH.SKLL_AUTHOR_CODE IS '0, 1, 2, 3 ... 추가 가능';

CREATE UNIQUE INDEX PK_SKILL_AUTH
	ON SKILL_AUTH (
		EMPL_NO ASC,
		SKLL_CODE ASC,
		SKLL_AUTHOR_CODE ASC
	);

ALTER TABLE SKILL_AUTH
	ADD
		CONSTRAINT PK_SKILL_AUTH
		PRIMARY KEY (
			EMPL_NO,
			SKLL_CODE,
			SKLL_AUTHOR_CODE
		);

CREATE TABLE COMMON_CODE (
	CMMN_CODE_GROUP VARCHAR2(100) NOT NULL,
	CMMN_CODE VARCHAR2(2) NOT NULL,
	CMMN_CODE_NM VARCHAR2(100) NOT NULL,
	CMMN_CODE_DC VARCHAR2(200) NOT NULL,
	USE_YN VARCHAR2(1),
	UPPER_CMMN_CODE VARCHAR2(2),
	CMMN_CODE_SN NUMBER
);

COMMENT ON TABLE COMMON_CODE IS '공통코드';

COMMENT ON COLUMN COMMON_CODE.CMMN_CODE_GROUP IS '공통 코드 그룹';

COMMENT ON COLUMN COMMON_CODE.CMMN_CODE IS '공통 코드';

COMMENT ON COLUMN COMMON_CODE.CMMN_CODE_NM IS '공통 코드 명';

COMMENT ON COLUMN COMMON_CODE.CMMN_CODE_DC IS '공통 코드 설명';

COMMENT ON COLUMN COMMON_CODE.USE_YN IS '사용 여부';

COMMENT ON COLUMN COMMON_CODE.UPPER_CMMN_CODE IS '상위 공통 코드';

COMMENT ON COLUMN COMMON_CODE.CMMN_CODE_SN IS '공통 코드 순번';

CREATE UNIQUE INDEX PK_COMMON_CODE
	ON COMMON_CODE (
		CMMN_CODE_GROUP ASC,
		CMMN_CODE ASC
	);

ALTER TABLE COMMON_CODE
	ADD
		CONSTRAINT PK_COMMON_CODE
		PRIMARY KEY (
			CMMN_CODE_GROUP,
			CMMN_CODE
		);

CREATE TABLE ATTATCH_FILE (
	ATCH_FILE_NO NUMBER NOT NULL,
	FILE_SN NUMBER NOT NULL,
	FILE_STRE_PATH VARCHAR2(300) NOT NULL,
	FILE_NM VARCHAR2(300) NOT NULL,
	FILE_STRE_NM VARCHAR2(300) NOT NULL,
	FILE_EXTSN VARCHAR2(300) NOT NULL,
	FILE_MIME VARCHAR2(100),
	FILE_SIZE NUMBER NOT NULL,
	FILE_VIEW_SIZE VARCHAR2(30),
	DWLD_CO NUMBER,
	EMPL_NO VARCHAR2(8),
	FILE_USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
	FILE_CREAT_DT DATE
);

COMMENT ON TABLE ATTATCH_FILE IS '파일첨부';

COMMENT ON COLUMN ATTATCH_FILE.ATCH_FILE_NO IS '첨부 파일 번호';

COMMENT ON COLUMN ATTATCH_FILE.FILE_SN IS '파일 순번';

COMMENT ON COLUMN ATTATCH_FILE.FILE_STRE_PATH IS '파일이 있는 위치';

COMMENT ON COLUMN ATTATCH_FILE.FILE_NM IS '실제 파일 명';

COMMENT ON COLUMN ATTATCH_FILE.FILE_STRE_NM IS '파일 저장 명';

COMMENT ON COLUMN ATTATCH_FILE.FILE_EXTSN IS '파일 확장자';

COMMENT ON COLUMN ATTATCH_FILE.FILE_MIME IS '파일 미디어 타입';

COMMENT ON COLUMN ATTATCH_FILE.FILE_SIZE IS '파일 사이즈';

COMMENT ON COLUMN ATTATCH_FILE.FILE_VIEW_SIZE IS '파일 KB/ Mb 사이즈 변환';

COMMENT ON COLUMN ATTATCH_FILE.DWLD_CO IS '다운로드 횟수';

COMMENT ON COLUMN ATTATCH_FILE.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN ATTATCH_FILE.FILE_USE_YN IS 'Y / N';

COMMENT ON COLUMN ATTATCH_FILE.FILE_CREAT_DT IS '파일 생성 일시';

CREATE UNIQUE INDEX PK_ATTATCH_FILE
	ON ATTATCH_FILE (
		ATCH_FILE_NO ASC,
		FILE_SN ASC
	);

ALTER TABLE ATTATCH_FILE
	ADD
		CONSTRAINT PK_ATTATCH_FILE
		PRIMARY KEY (
			ATCH_FILE_NO,
			FILE_SN
		);

CREATE TABLE DCLZ_TYPE (
	EMPL_NO VARCHAR2(8) NOT NULL,
	DCLZ_NO VARCHAR2(8) NOT NULL,
	DCLZ_CODE VARCHAR2(2) NOT NULL,
	DCLZ_BEGIN_DT DATE,
	DCLZ_END_DT DATE
);

COMMENT ON TABLE DCLZ_TYPE IS '근태  특이사항';

COMMENT ON COLUMN DCLZ_TYPE.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN DCLZ_TYPE.DCLZ_NO IS '20250325';

COMMENT ON COLUMN DCLZ_TYPE.DCLZ_CODE IS 'ATTEND';

COMMENT ON COLUMN DCLZ_TYPE.DCLZ_BEGIN_DT IS '근태 시작 일시';

COMMENT ON COLUMN DCLZ_TYPE.DCLZ_END_DT IS '근태 종료 일시';

CREATE UNIQUE INDEX PK_DCLZ_TYPE
	ON DCLZ_TYPE (
		EMPL_NO ASC,
		DCLZ_NO ASC,
		DCLZ_CODE ASC
	);

ALTER TABLE DCLZ_TYPE
	ADD
		CONSTRAINT PK_DCLZ_TYPE
		PRIMARY KEY (
			EMPL_NO,
			DCLZ_NO,
			DCLZ_CODE
		);

CREATE TABLE VACATION (
	EMPL_NO VARCHAR2(8) NOT NULL,
	YRYC_YEAR VARCHAR2(4) NOT NULL,
	YRYC_USE_BEGIN_DATE VARCHAR2(8),
	YRYC_USE_END_DATE VARCHAR2(8),
	TOT_YRYC_DAYCNT NUMBER NOT NULL,
	YRYC_USE_DAYCNT NUMBER NOT NULL,
	YRYC_MDAT_DAYCNT NUMBER
);

COMMENT ON TABLE VACATION IS '연차';

COMMENT ON COLUMN VACATION.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN VACATION.YRYC_YEAR IS '2025/ 2024';

COMMENT ON COLUMN VACATION.YRYC_USE_BEGIN_DATE IS '이번년도 입사자는 입사년도 사용';

COMMENT ON COLUMN VACATION.YRYC_USE_END_DATE IS '20250101';

COMMENT ON COLUMN VACATION.TOT_YRYC_DAYCNT IS '총 연차 일수';

COMMENT ON COLUMN VACATION.YRYC_USE_DAYCNT IS '연차 사용 일수';

COMMENT ON COLUMN VACATION.YRYC_MDAT_DAYCNT IS '연차 조정 일수';

CREATE UNIQUE INDEX PK_VACATION
	ON VACATION (
		EMPL_NO ASC,
		YRYC_YEAR ASC
	);

ALTER TABLE VACATION
	ADD
		CONSTRAINT PK_VACATION
		PRIMARY KEY (
			EMPL_NO,
			YRYC_YEAR
		);

CREATE TABLE ATRZ (
	ATRZ_DOC_NO VARCHAR2(50) NOT NULL,
	DRAFTER_EMPNO VARCHAR2(8) NOT NULL,
	DRAFTER_CLSF VARCHAR2(2) NOT NULL,
	BKMK_YN VARCHAR2(1) NOT NULL,
	ATCH_FILE_NO NUMBER,
	ATRZ_SJ VARCHAR2(200) NOT NULL,
	ATRZ_CN CLOB NOT NULL,
	ATRZ_OPINION VARCHAR2(1000),
	ATRZ_TMPR_STRE_DT DATE,
	ATRZ_DRFT_DT DATE,
	ATRZ_COMPT_DT DATE,
	ATRZ_RTRVL_DT DATE,
	ATRZ_STTUS_CODE VARCHAR2(2),
	ELTSGN_IMAGE VARCHAR2(2000),
	DOC_FORM_NO NUMBER,
	ATRZ_DELETE_YN VARCHAR2(1)
);

COMMENT ON TABLE ATRZ IS '전자결재';

COMMENT ON COLUMN ATRZ.ATRZ_DOC_NO IS 'H-2025-03-20_0001';

COMMENT ON COLUMN ATRZ.DRAFTER_EMPNO IS '기안자 사번';

COMMENT ON COLUMN ATRZ.DRAFTER_CLSF IS '기안자 직급';

COMMENT ON COLUMN ATRZ.BKMK_YN IS 'Y / N';

COMMENT ON COLUMN ATRZ.ATCH_FILE_NO IS '첨부 파일 번호';

COMMENT ON COLUMN ATRZ.ATRZ_SJ IS '전자결재 제목';

COMMENT ON COLUMN ATRZ.ATRZ_CN IS '작성완료한 문서 내용이 들어감';

COMMENT ON COLUMN ATRZ.ATRZ_OPINION IS '전자결재 의견';

COMMENT ON COLUMN ATRZ.ATRZ_TMPR_STRE_DT IS '전자결재 임시저장 일시';

COMMENT ON COLUMN ATRZ.ATRZ_DRFT_DT IS '진행중';

COMMENT ON COLUMN ATRZ.ATRZ_COMPT_DT IS '반려, 완료, 취소';

COMMENT ON COLUMN ATRZ.ATRZ_RTRVL_DT IS '회수';

COMMENT ON COLUMN ATRZ.ATRZ_STTUS_CODE IS '00 진행중 / 10 반려 / 20 완료  / 30 회수(상신취소) / 40 취소';

COMMENT ON COLUMN ATRZ.ELTSGN_IMAGE IS '이미지는 BASE64';

COMMENT ON COLUMN ATRZ.DOC_FORM_NO IS '문서 양식 번호';

COMMENT ON COLUMN ATRZ.ATRZ_DELETE_YN IS 'Y / N';

CREATE UNIQUE INDEX PK_ATRZ
	ON ATRZ (
		ATRZ_DOC_NO ASC
	);

ALTER TABLE ATRZ
	ADD
		CONSTRAINT PK_ATRZ
		PRIMARY KEY (
			ATRZ_DOC_NO
		);

CREATE TABLE ATRZ_LINE (
	ATRZ_DOC_NO VARCHAR2(50) NOT NULL,
	ATRZ_LN_SN NUMBER NOT NULL,
	SANCTNER_EMPNO VARCHAR2(8) NOT NULL,
	SANCTNER_CLSF_CODE VARCHAR2(2),
	CONTD_EMPNO VARCHAR2(8),
	CONTD_CLSF_CODE VARCHAR2(2),
	DCRB_MAN_EMPNO VARCHAR2(8),
	DCRB_MAN_CLSF_CODE VARCHAR2(2),
	ATRZ_TY VARCHAR2(1) NOT NULL,
	SANCTN_PROGRS_STTUS_CODE VARCHAR2(2) NOT NULL,
	DCRB_AUTHOR_YN VARCHAR2(1) NOT NULL,
	CONTD_AUTHOR_YN VARCHAR2(1),
	SANCTN_OPINION VARCHAR2(1000),
	ELTSGN_IMAGE VARCHAR2(2000),
	SANCTN_CONFM_DT DATE
);

COMMENT ON TABLE ATRZ_LINE IS '전자결재 선';

COMMENT ON COLUMN ATRZ_LINE.ATRZ_DOC_NO IS '전자결재 문서 번호';

COMMENT ON COLUMN ATRZ_LINE.ATRZ_LN_SN IS '전자결재 선 순번';

COMMENT ON COLUMN ATRZ_LINE.SANCTNER_EMPNO IS '처음 결재를 요청 받은 사번';

COMMENT ON COLUMN ATRZ_LINE.SANCTNER_CLSF_CODE IS '결재자 직급 코드';

COMMENT ON COLUMN ATRZ_LINE.CONTD_EMPNO IS '대신 결재하는 사원 넘버';

COMMENT ON COLUMN ATRZ_LINE.CONTD_CLSF_CODE IS '대결자 직급 코드';

COMMENT ON COLUMN ATRZ_LINE.DCRB_MAN_EMPNO IS '전결 해준 사원 번호';

COMMENT ON COLUMN ATRZ_LINE.DCRB_MAN_CLSF_CODE IS '전결자 직급 코드';

COMMENT ON COLUMN ATRZ_LINE.ATRZ_TY IS '0 결재 1 참조';

COMMENT ON COLUMN ATRZ_LINE.SANCTN_PROGRS_STTUS_CODE IS '00 대기중, 10 승인, 20 반려, 30 전결, 40 대결';

COMMENT ON COLUMN ATRZ_LINE.DCRB_AUTHOR_YN IS 'Y / N';

COMMENT ON COLUMN ATRZ_LINE.CONTD_AUTHOR_YN IS 'Y / N';

COMMENT ON COLUMN ATRZ_LINE.SANCTN_OPINION IS '반려를 선택한 경우는 필수';

COMMENT ON COLUMN ATRZ_LINE.ELTSGN_IMAGE IS '이미지는 BASE64';

COMMENT ON COLUMN ATRZ_LINE.SANCTN_CONFM_DT IS '결재 승인 일시';

CREATE UNIQUE INDEX PK_ATRZ_LINE
	ON ATRZ_LINE (
		ATRZ_DOC_NO ASC,
		ATRZ_LN_SN ASC
	);

ALTER TABLE ATRZ_LINE
	ADD
		CONSTRAINT PK_ATRZ_LINE
		PRIMARY KEY (
			ATRZ_DOC_NO,
			ATRZ_LN_SN
		);

CREATE TABLE DOC_FORM (
	DOC_FORM_NO NUMBER NOT NULL,
	DOC_FORM_NM VARCHAR2(200) NOT NULL,
	DOC_FORM_CN CLOB NOT NULL,
	DOC_USE_YN VARCHAR2(1) NOT NULL,
	PARNTS_DOC_FORM_NO NUMBER
);

COMMENT ON TABLE DOC_FORM IS '문서 양식';

COMMENT ON COLUMN DOC_FORM.DOC_FORM_NO IS '문서 양식 번호';

COMMENT ON COLUMN DOC_FORM.DOC_FORM_NM IS '문서 양식 명';

COMMENT ON COLUMN DOC_FORM.DOC_FORM_CN IS '문서 양식 내용';

COMMENT ON COLUMN DOC_FORM.DOC_USE_YN IS 'Y/N';

COMMENT ON COLUMN DOC_FORM.PARNTS_DOC_FORM_NO IS '부모 문서 양식 번호';

CREATE UNIQUE INDEX PK_DOC_FORM
	ON DOC_FORM (
		DOC_FORM_NO ASC
	);

ALTER TABLE DOC_FORM
	ADD
		CONSTRAINT PK_DOC_FORM
		PRIMARY KEY (
			DOC_FORM_NO
		);

CREATE TABLE VACTION_PLAN (
	VCATN_ACTPLN_NO NUMBER NOT NULL,
	ATRZ_DOC_NO VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE VACTION_PLAN IS '휴가계획서';

COMMENT ON COLUMN VACTION_PLAN.VCATN_ACTPLN_NO IS '휴가 계획서 번호';

COMMENT ON COLUMN VACTION_PLAN.ATRZ_DOC_NO IS '전자결재 문서 번호';

CREATE UNIQUE INDEX PK_VACTION_PLAN
	ON VACTION_PLAN (
		VCATN_ACTPLN_NO ASC
	);

ALTER TABLE VACTION_PLAN
	ADD
		CONSTRAINT PK_VACTION_PLAN
		PRIMARY KEY (
			VCATN_ACTPLN_NO
		);

CREATE TABLE ATRZ_LIKE (
	ATRZ_LN_BKMK_NO NUMBER NOT NULL,
	SANCTN_LN_BKMK_NM VARCHAR2(100) NOT NULL,
	BKMK_CREAT_DATE VARCHAR2(8) NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL
);

COMMENT ON TABLE ATRZ_LIKE IS '전자결재 선 즐겨찾기';

COMMENT ON COLUMN ATRZ_LIKE.ATRZ_LN_BKMK_NO IS '전자결재 선 즐겨찾기 번호';

COMMENT ON COLUMN ATRZ_LIKE.SANCTN_LN_BKMK_NM IS '결재선 즐겨찾기 이름';

COMMENT ON COLUMN ATRZ_LIKE.BKMK_CREAT_DATE IS '즐겨찾기 생성 일자';

COMMENT ON COLUMN ATRZ_LIKE.EMPL_NO IS '사원 번호';

CREATE UNIQUE INDEX PK_ATRZ_LIKE
	ON ATRZ_LIKE (
		ATRZ_LN_BKMK_NO ASC
	);

ALTER TABLE ATRZ_LIKE
	ADD
		CONSTRAINT PK_ATRZ_LIKE
		PRIMARY KEY (
			ATRZ_LN_BKMK_NO
		);

CREATE TABLE ATRZ_EMP (
	ATRZ_LN_BKMK_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	ATRZ_SN NUMBER NOT NULL,
	ATRZ_TY VARCHAR2(1) NOT NULL
);

COMMENT ON TABLE ATRZ_EMP IS '즐겨찾기 결재선 사원들';

COMMENT ON COLUMN ATRZ_EMP.ATRZ_LN_BKMK_NO IS '전자결재 선 즐겨찾기 번호';

COMMENT ON COLUMN ATRZ_EMP.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN ATRZ_EMP.ATRZ_SN IS '전자결재 순번';

COMMENT ON COLUMN ATRZ_EMP.ATRZ_TY IS '0 결재 1 참조';

CREATE UNIQUE INDEX PK_ATRZ_EMP
	ON ATRZ_EMP (
		ATRZ_LN_BKMK_NO ASC,
		EMPL_NO ASC
	);

ALTER TABLE ATRZ_EMP
	ADD
		CONSTRAINT PK_ATRZ_EMP
		PRIMARY KEY (
			ATRZ_LN_BKMK_NO,
			EMPL_NO
		);

CREATE TABLE SCHEDULE (
	SCHDUL_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	LBL_COLOR_NO NUMBER,
	SCHDUL_TY VARCHAR2(300),
	SCHDUL_SJ VARCHAR2(100) NOT NULL,
	SCHDUL_CN VARCHAR2(2000) NOT NULL,
	SCHDUL_BEGIN_DT DATE NOT NULL,
	SCHDUL_END_DT DATE NOT NULL,
	SCHDUL_PLACE VARCHAR2(1000),
	ORIGIN_PATH VARCHAR2(30),
	SKLL_CTGRY_TY NUMBER
);

COMMENT ON TABLE SCHEDULE IS '일정';

COMMENT ON COLUMN SCHEDULE.SCHDUL_NO IS '일정 번호';

COMMENT ON COLUMN SCHEDULE.EMPL_NO IS '일정을 작성한 사원 번호';

COMMENT ON COLUMN SCHEDULE.LBL_COLOR_NO IS '라벨 색상 넘버';

COMMENT ON COLUMN SCHEDULE.SCHDUL_TY IS '0 개인, 1 전체';

COMMENT ON COLUMN SCHEDULE.SCHDUL_SJ IS '일정 제목';

COMMENT ON COLUMN SCHEDULE.SCHDUL_CN IS '일정 내용';

COMMENT ON COLUMN SCHEDULE.SCHDUL_BEGIN_DT IS '일정 시작 일시';

COMMENT ON COLUMN SCHEDULE.SCHDUL_END_DT IS '일정 종료 일시';

COMMENT ON COLUMN SCHEDULE.SCHDUL_PLACE IS '일정 장소';

COMMENT ON COLUMN SCHEDULE.ORIGIN_PATH IS '기능별 NO';

COMMENT ON COLUMN SCHEDULE.SKLL_CTGRY_TY IS '기능 NO';

CREATE UNIQUE INDEX PK_SCHEDULE
	ON SCHEDULE (
		SCHDUL_NO ASC
	);

ALTER TABLE SCHEDULE
	ADD
		CONSTRAINT PK_SCHEDULE
		PRIMARY KEY (
			SCHDUL_NO
		);

CREATE TABLE SCHEDULE_AUTH_GROUP (
	SCHDUL_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	DEPT_CODE VARCHAR2(2),
	SCHDUL_CNFIRM_AT VARCHAR2(1) DEFAULT 'N'
);

COMMENT ON TABLE SCHEDULE_AUTH_GROUP IS '일정 공개 그룹';

COMMENT ON COLUMN SCHEDULE_AUTH_GROUP.SCHDUL_NO IS '일정 번호';

COMMENT ON COLUMN SCHEDULE_AUTH_GROUP.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN SCHEDULE_AUTH_GROUP.DEPT_CODE IS '공통 코드에서 기져옴';

COMMENT ON COLUMN SCHEDULE_AUTH_GROUP.SCHDUL_CNFIRM_AT IS 'Y / N';

CREATE UNIQUE INDEX PK_SCHEDULE_AUTH_GROUP
	ON SCHEDULE_AUTH_GROUP (
		SCHDUL_NO ASC
	);

ALTER TABLE SCHEDULE_AUTH_GROUP
	ADD
		CONSTRAINT PK_SCHEDULE_AUTH_GROUP
		PRIMARY KEY (
			SCHDUL_NO
		);

CREATE TABLE SCHEDULE_TYPE (
	SCHDUL_NO NUMBER NOT NULL
);

COMMENT ON TABLE SCHEDULE_TYPE IS '일정 등록 유형';

COMMENT ON COLUMN SCHEDULE_TYPE.SCHDUL_NO IS '일정 번호';

CREATE UNIQUE INDEX PK_SCHEDULE_TYPE
	ON SCHEDULE_TYPE (
		SCHDUL_NO ASC
	);

ALTER TABLE SCHEDULE_TYPE
	ADD
		CONSTRAINT PK_SCHEDULE_TYPE
		PRIMARY KEY (
			SCHDUL_NO
		);

CREATE TABLE MAIL (
	EMAIL_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	LBL_NO NUMBER,
	EMAIL_TRNSMIS_TY VARCHAR2(1),
	EMAIL_CL_TY VARCHAR2(1) NOT NULL,
	TRNSMIT_EMAIL VARCHAR2(200),
	RECPTN_EMAIL VARCHAR2(200),
	EMAIL_SJ VARCHAR2(300) NOT NULL,
	EMAIL_CN CLOB NOT NULL,
	ATCH_FILE_NO NUMBER,
	TRNSMIT_DT DATE,
	READNG_AT CHAR(1)
);

COMMENT ON TABLE MAIL IS '메일함';

COMMENT ON COLUMN MAIL.EMAIL_NO IS '메일 넘버';

COMMENT ON COLUMN MAIL.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN MAIL.LBL_NO IS '라벨 번호';

COMMENT ON COLUMN MAIL.EMAIL_TRNSMIS_TY IS '0 보낸메일, 1 받은메일, 2 참조, 3 숨은 참조';

COMMENT ON COLUMN MAIL.EMAIL_CL_TY IS '0 보낸메일, 1 받은메일, 2 임시메일, 3 스팸함, 4 휴지통';

COMMENT ON COLUMN MAIL.TRNSMIT_EMAIL IS '송신 이메일';

COMMENT ON COLUMN MAIL.RECPTN_EMAIL IS '수신 이메일';

COMMENT ON COLUMN MAIL.EMAIL_SJ IS '메일 제목';

COMMENT ON COLUMN MAIL.EMAIL_CN IS '메일 내용';

COMMENT ON COLUMN MAIL.ATCH_FILE_NO IS '첨부 파일 번호';

COMMENT ON COLUMN MAIL.TRNSMIT_DT IS '송신 일시';

COMMENT ON COLUMN MAIL.READNG_AT IS 'Y / N';

CREATE UNIQUE INDEX PK_MAIL
	ON MAIL (
		EMAIL_NO ASC,
		EMPL_NO ASC
	);

ALTER TABLE MAIL
	ADD
		CONSTRAINT PK_MAIL
		PRIMARY KEY (
			EMAIL_NO,
			EMPL_NO
		);

CREATE TABLE MAIL_LABEL (
	LBL_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	LBL_NM VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE MAIL_LABEL IS '메일 라벨';

COMMENT ON COLUMN MAIL_LABEL.LBL_NO IS '라벨 번호';

COMMENT ON COLUMN MAIL_LABEL.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN MAIL_LABEL.LBL_NM IS '라벨명';

CREATE UNIQUE INDEX PK_MAIL_LABEL
	ON MAIL_LABEL (
		LBL_NO ASC
	);

ALTER TABLE MAIL_LABEL
	ADD
		CONSTRAINT PK_MAIL_LABEL
		PRIMARY KEY (
			LBL_NO
		);

CREATE TABLE MAIL_TEMPLATE (
	EMAIL_ATMC_CMPLT_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	FORM_CN CLOB NOT NULL,
	RAISNG_USE_CO NUMBER
);

COMMENT ON TABLE MAIL_TEMPLATE IS '메일 자동완성';

COMMENT ON COLUMN MAIL_TEMPLATE.EMAIL_ATMC_CMPLT_NO IS '메일 자동완성 번호';

COMMENT ON COLUMN MAIL_TEMPLATE.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN MAIL_TEMPLATE.FORM_CN IS '양식 내용';

COMMENT ON COLUMN MAIL_TEMPLATE.RAISNG_USE_CO IS '많이 사용한 템플릿을 먼저 보여줌';

CREATE UNIQUE INDEX PK_MAIL_TEMPLATE
	ON MAIL_TEMPLATE (
		EMAIL_ATMC_CMPLT_NO ASC
	);

ALTER TABLE MAIL_TEMPLATE
	ADD
		CONSTRAINT PK_MAIL_TEMPLATE
		PRIMARY KEY (
			EMAIL_ATMC_CMPLT_NO
		);

CREATE TABLE PROJECT (
	PRJCT_NO NUMBER NOT NULL,
	CTGRY_NO NUMBER NOT NULL,
	PRJCT_NM VARCHAR2(300) NOT NULL,
	PRJCT_CN CLOB NOT NULL,
	PRJCT_STTUS VARCHAR2(1) NOT NULL,
	PRJCT_GRAD VARCHAR2(1) NOT NULL,
	PRJCT_ADRES VARCHAR2(500),
	PRJCT_URL VARCHAR2(500),
	PRJCT_RCVORD_AMOUNT NUMBER,
	PRJCT_BEGIN_DATE VARCHAR2(8),
	PRJCT_END_DATE VARCHAR2(8)
);

COMMENT ON TABLE PROJECT IS '프로젝트';

COMMENT ON COLUMN PROJECT.PRJCT_NO IS '프로젝트 번호';

COMMENT ON COLUMN PROJECT.CTGRY_NO IS '카테고리 번호';

COMMENT ON COLUMN PROJECT.PRJCT_NM IS '프로젝트 명';

COMMENT ON COLUMN PROJECT.PRJCT_CN IS '프로젝트 내용';

COMMENT ON COLUMN PROJECT.PRJCT_STTUS IS '0 대기, 1 진행중, 2 완료 3 취소';

COMMENT ON COLUMN PROJECT.PRJCT_GRAD IS 'A ~ E';

COMMENT ON COLUMN PROJECT.PRJCT_ADRES IS '다음 주소를 활용해서 넣기';

COMMENT ON COLUMN PROJECT.PRJCT_URL IS '프로젝트 ';

COMMENT ON COLUMN PROJECT.PRJCT_RCVORD_AMOUNT IS '프로젝트 수주금액';

COMMENT ON COLUMN PROJECT.PRJCT_BEGIN_DATE IS '프로젝트 시작 일자';

COMMENT ON COLUMN PROJECT.PRJCT_END_DATE IS '프로젝트 종료 일자';

CREATE UNIQUE INDEX PK_PROJECT
	ON PROJECT (
		PRJCT_NO ASC
	);

ALTER TABLE PROJECT
	ADD
		CONSTRAINT PK_PROJECT
		PRIMARY KEY (
			PRJCT_NO
		);

CREATE TABLE PROJECT_EMP (
	PRJCT_NO NUMBER NOT NULL,
	PRTCPNT_EMPNO VARCHAR2(8) NOT NULL,
	PRTCPNT_ROLE VARCHAR2(1) NOT NULL,
	PRJCT_AUTHOR VARCHAR2(4) NOT NULL,
	EVL_MAN_EMPNO VARCHAR2(8),
	EVL_CN VARCHAR2(2000) NOT NULL,
	EVL_GRAD VARCHAR2(1) NOT NULL,
	EVL_WRITNG_DT DATE NOT NULL,
	EVL_UPDT_DT DATE,
	SECSN_YN VARCHAR2(1)
);

COMMENT ON TABLE PROJECT_EMP IS '프로젝트 참여자';

COMMENT ON COLUMN PROJECT_EMP.PRJCT_NO IS '프로젝트 번호';

COMMENT ON COLUMN PROJECT_EMP.PRTCPNT_EMPNO IS '참여자 사번';

COMMENT ON COLUMN PROJECT_EMP.PRTCPNT_ROLE IS '0 책임자, 1 참여자, 2 참조자';

COMMENT ON COLUMN PROJECT_EMP.PRJCT_AUTHOR IS '0000 / 0001 / 0011 / 이런 식';

COMMENT ON COLUMN PROJECT_EMP.EVL_MAN_EMPNO IS '여기에 평가할 사번 추가 (기본으로 책임자, 아닌 경우 위임 가능)';

COMMENT ON COLUMN PROJECT_EMP.EVL_CN IS '평가 내용';

COMMENT ON COLUMN PROJECT_EMP.EVL_GRAD IS '1 ~ 5';

COMMENT ON COLUMN PROJECT_EMP.EVL_WRITNG_DT IS '평가 작성 일시';

COMMENT ON COLUMN PROJECT_EMP.EVL_UPDT_DT IS '평가 수정 일시';

COMMENT ON COLUMN PROJECT_EMP.SECSN_YN IS 'Y / N';

CREATE UNIQUE INDEX PK_PROJECT_EMP
	ON PROJECT_EMP (
		PRJCT_NO ASC,
		PRTCPNT_EMPNO ASC
	);

ALTER TABLE PROJECT_EMP
	ADD
		CONSTRAINT PK_PROJECT_EMP
		PRIMARY KEY (
			PRJCT_NO,
			PRTCPNT_EMPNO
		);

CREATE TABLE PROJECT_TASK (
	TASK_NO NUMBER NOT NULL,
	PRJCT_NO NUMBER NOT NULL,
	UPPER_TASK_NO NUMBER,
	CHARGER_EMPNO VARCHAR2(8) NOT NULL,
	TASK_NM VARCHAR2(300) NOT NULL,
	TASK_CN CLOB,
	PRIORT VARCHAR(2) NOT NULL,
	TASK_GRAD VARCHAR2(1) NOT NULL,
	PROGRSRT NUMBER(3) NOT NULL,
	TASK_STTUS VARCHAR(2) NOT NULL,
	ATCH_FILE_NO NUMBER,
	TASK_BEGIN_DT DATE,
	TASK_DAYCNT NUMBER,
	TASK_END_DT DATE
);

COMMENT ON TABLE PROJECT_TASK IS '프로젝트 과제';

COMMENT ON COLUMN PROJECT_TASK.TASK_NO IS '과제 번호';

COMMENT ON COLUMN PROJECT_TASK.PRJCT_NO IS '프로젝트 번호';

COMMENT ON COLUMN PROJECT_TASK.UPPER_TASK_NO IS '상위 과제 번호';

COMMENT ON COLUMN PROJECT_TASK.CHARGER_EMPNO IS '담당자 사번';

COMMENT ON COLUMN PROJECT_TASK.TASK_NM IS '과제 명';

COMMENT ON COLUMN PROJECT_TASK.TASK_CN IS '과제 내용';

COMMENT ON COLUMN PROJECT_TASK.PRIORT IS '0 낮음 1 보통 2 높음 3 긴급';

COMMENT ON COLUMN PROJECT_TASK.TASK_GRAD IS 'A ~ E';

COMMENT ON COLUMN PROJECT_TASK.PROGRSRT IS '0 ~ 100';

COMMENT ON COLUMN PROJECT_TASK.TASK_STTUS IS '0 대기, 1 진행중, 2 완료 3 피드백 4. 변경';

COMMENT ON COLUMN PROJECT_TASK.ATCH_FILE_NO IS '첨부 파일 번호';

COMMENT ON COLUMN PROJECT_TASK.TASK_BEGIN_DT IS '과제 시작 일시';

COMMENT ON COLUMN PROJECT_TASK.TASK_DAYCNT IS 'duration 과제 시작일 부터 종료일까지의 일수';

COMMENT ON COLUMN PROJECT_TASK.TASK_END_DT IS '종료 일시는 과제 시작일시 + 과제일수로 계산한다';

CREATE UNIQUE INDEX PK_PROJECT_TASK
	ON PROJECT_TASK (
		TASK_NO ASC
	);

ALTER TABLE PROJECT_TASK
	ADD
		CONSTRAINT PK_PROJECT_TASK
		PRIMARY KEY (
			TASK_NO
		);

CREATE TABLE BBS (
	BBS_SN NUMBER NOT NULL,
	BBS_CTGRY_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	BBSCTT_SJ VARCHAR2(200),
	BBSCTT_CN CLOB NOT NULL,
	BBSCTT_CREAT_DT DATE,
	BBSCTT_UPDT_DT DATE,
	RDCNT NUMBER,
	BBSCTT_USE_YN VARCHAR2(1),
	BBSCTT_DELETE_YN VARCHAR2(1) NOT NULL,
	UPEND_FIXING_YN VARCHAR2(1),
	ATCH_FILE_NO NUMBER
);

COMMENT ON TABLE BBS IS '게시판';

COMMENT ON COLUMN BBS.BBS_SN IS '게시판 순번';

COMMENT ON COLUMN BBS.BBS_CTGRY_NO IS '게시판 카테고리 번호';

COMMENT ON COLUMN BBS.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN BBS.BBSCTT_SJ IS '게시글 제목';

COMMENT ON COLUMN BBS.BBSCTT_CN IS '게시글 내용';

COMMENT ON COLUMN BBS.BBSCTT_CREAT_DT IS '게시글 생성 일시';

COMMENT ON COLUMN BBS.BBSCTT_UPDT_DT IS '게시글 수정 일시';

COMMENT ON COLUMN BBS.RDCNT IS '조회수';

COMMENT ON COLUMN BBS.BBSCTT_USE_YN IS 'Y/N';

COMMENT ON COLUMN BBS.BBSCTT_DELETE_YN IS 'Y/N';

COMMENT ON COLUMN BBS.UPEND_FIXING_YN IS 'Y/N';

COMMENT ON COLUMN BBS.ATCH_FILE_NO IS '첨부 파일 번호';

CREATE UNIQUE INDEX PK_BBS
	ON BBS (
		BBS_SN ASC,
		BBS_CTGRY_NO ASC
	);

ALTER TABLE BBS
	ADD
		CONSTRAINT PK_BBS
		PRIMARY KEY (
			BBS_SN,
			BBS_CTGRY_NO
		);

CREATE TABLE BBS_CTGRY (
	BBS_CTGRY_NO NUMBER NOT NULL,
	UPPER_CTGRY_NO NUMBER,
	CTGRY_NM VARCHAR2(30) NOT NULL,
	CTGRY_CREAT_DT DATE,
	CTGRY_USE_YN VARCHAR2(1),
	DEPT_CODE VARCHAR2(2)
);

COMMENT ON TABLE BBS_CTGRY IS '게시판 카테고리';

COMMENT ON COLUMN BBS_CTGRY.BBS_CTGRY_NO IS '게시판 카테고리 번호';

COMMENT ON COLUMN BBS_CTGRY.UPPER_CTGRY_NO IS '부모 카테고리 번호';

COMMENT ON COLUMN BBS_CTGRY.CTGRY_NM IS '카테고리 명';

COMMENT ON COLUMN BBS_CTGRY.CTGRY_CREAT_DT IS '카테고리 생성 일시';

COMMENT ON COLUMN BBS_CTGRY.CTGRY_USE_YN IS 'Y / N';

COMMENT ON COLUMN BBS_CTGRY.DEPT_CODE IS '부서 코드';

CREATE UNIQUE INDEX PK_BBS_CTGRY
	ON BBS_CTGRY (
		BBS_CTGRY_NO ASC
	);

ALTER TABLE BBS_CTGRY
	ADD
		CONSTRAINT PK_BBS_CTGRY
		PRIMARY KEY (
			BBS_CTGRY_NO
		);

CREATE TABLE BBS_ANSWER (
	ANSWER_NO NUMBER NOT NULL,
	BBS_SN NUMBER NOT NULL,
	BBS_CTGRY_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	ANSWER_CN VARCHAR2(1000),
	ANSWER_CREAT_DT DATE
);

COMMENT ON TABLE BBS_ANSWER IS '댓글';

COMMENT ON COLUMN BBS_ANSWER.ANSWER_NO IS '댓글 번호';

COMMENT ON COLUMN BBS_ANSWER.BBS_SN IS '게시판 순번';

COMMENT ON COLUMN BBS_ANSWER.BBS_CTGRY_NO IS '게시판 카테고리 번호';

COMMENT ON COLUMN BBS_ANSWER.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN BBS_ANSWER.ANSWER_CN IS '댓글 내용';

COMMENT ON COLUMN BBS_ANSWER.ANSWER_CREAT_DT IS '댓글 생성 일시';

CREATE UNIQUE INDEX PK_BBS_ANSWER
	ON BBS_ANSWER (
		ANSWER_NO ASC
	);

ALTER TABLE BBS_ANSWER
	ADD
		CONSTRAINT PK_BBS_ANSWER
		PRIMARY KEY (
			ANSWER_NO
		);

CREATE TABLE BBS_LIKE (
	BBS_SN NUMBER NOT NULL,
	BBS_CTGRY_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL
);

COMMENT ON TABLE BBS_LIKE IS '게시판 좋아요';

COMMENT ON COLUMN BBS_LIKE.BBS_SN IS '게시판 순번';

COMMENT ON COLUMN BBS_LIKE.BBS_CTGRY_NO IS '게시판 카테고리 번호';

COMMENT ON COLUMN BBS_LIKE.EMPL_NO IS '사원 번호';

CREATE UNIQUE INDEX PK_BBS_LIKE
	ON BBS_LIKE (
		BBS_SN ASC,
		BBS_CTGRY_NO ASC
	);

ALTER TABLE BBS_LIKE
	ADD
		CONSTRAINT PK_BBS_LIKE
		PRIMARY KEY (
			BBS_SN,
			BBS_CTGRY_NO
		);

CREATE TABLE CHAT_ROOM (
	CHTT_ROOM_NO NUMBER NOT NULL,
	CHTT_ROOM_NM VARCHAR(50) NOT NULL,
	CHTT_ROOM_TY VARCHAR(30) NOT NULL,
	LAST_MSSAGE_NO NUMBER,
	CHTT_CREAT_DT DATE
);

COMMENT ON TABLE CHAT_ROOM IS '채팅방';

COMMENT ON COLUMN CHAT_ROOM.CHTT_ROOM_NO IS '채팅 방 번호';

COMMENT ON COLUMN CHAT_ROOM.CHTT_ROOM_NM IS '채팅 방 이름';

COMMENT ON COLUMN CHAT_ROOM.CHTT_ROOM_TY IS '0 1:1, 1: 그룹 채팅';

COMMENT ON COLUMN CHAT_ROOM.LAST_MSSAGE_NO IS '마지막 메세지 번호';

COMMENT ON COLUMN CHAT_ROOM.CHTT_CREAT_DT IS '채팅 생성 일시';

CREATE UNIQUE INDEX PK_CHAT_ROOM
	ON CHAT_ROOM (
		CHTT_ROOM_NO ASC
	);

ALTER TABLE CHAT_ROOM
	ADD
		CONSTRAINT PK_CHAT_ROOM
		PRIMARY KEY (
			CHTT_ROOM_NO
		);

CREATE TABLE CHAT_EMP (
	CHTT_ROOM_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	LAST_CNFIRM_NO NUMBER,
	PARTCPTN_DT DATE NOT NULL,
	OUT_DT DATE,
	USE_YN CHAR(1)
);

COMMENT ON TABLE CHAT_EMP IS '채팅 참여자';

COMMENT ON COLUMN CHAT_EMP.CHTT_ROOM_NO IS '채팅 방 번호';

COMMENT ON COLUMN CHAT_EMP.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN CHAT_EMP.LAST_CNFIRM_NO IS '마지막 확인 번호';

COMMENT ON COLUMN CHAT_EMP.PARTCPTN_DT IS '참여 일시';

COMMENT ON COLUMN CHAT_EMP.OUT_DT IS '채팅창 나가는 일시';

COMMENT ON COLUMN CHAT_EMP.USE_YN IS 'Y / N';

CREATE UNIQUE INDEX PK_CHAT_EMP
	ON CHAT_EMP (
		CHTT_ROOM_NO ASC,
		EMPL_NO ASC
	);

ALTER TABLE CHAT_EMP
	ADD
		CONSTRAINT PK_CHAT_EMP
		PRIMARY KEY (
			CHTT_ROOM_NO,
			EMPL_NO
		);

CREATE TABLE CHAT_MESSAGE (
	CHTT_ROOM_NO NUMBER NOT NULL,
	MSSAGE_SN NUMBER NOT NULL,
	MSSAGE_WRITNG_EMPNO VARCHAR2(8) NOT NULL,
	MSSAGE_CN NVARCHAR2(2000) NOT NULL,
	MSSAGE_TY VARCHAR(30) NOT NULL,
	MSSAGE_CREAT_DT DATE
);

COMMENT ON TABLE CHAT_MESSAGE IS '메세지';

COMMENT ON COLUMN CHAT_MESSAGE.CHTT_ROOM_NO IS '채팅 방 번호';

COMMENT ON COLUMN CHAT_MESSAGE.MSSAGE_SN IS '메세지 순번';

COMMENT ON COLUMN CHAT_MESSAGE.MSSAGE_WRITNG_EMPNO IS '메세지 작성 사번';

COMMENT ON COLUMN CHAT_MESSAGE.MSSAGE_CN IS '메세지 내용';

COMMENT ON COLUMN CHAT_MESSAGE.MSSAGE_TY IS '0 메세지 1 파일';

COMMENT ON COLUMN CHAT_MESSAGE.MSSAGE_CREAT_DT IS '메세지 생성 일시';

CREATE UNIQUE INDEX PK_CHAT_MESSAGE
	ON CHAT_MESSAGE (
		CHTT_ROOM_NO ASC,
		MSSAGE_SN ASC
	);

ALTER TABLE CHAT_MESSAGE
	ADD
		CONSTRAINT PK_CHAT_MESSAGE
		PRIMARY KEY (
			CHTT_ROOM_NO,
			MSSAGE_SN
		);

CREATE TABLE NOTIFICATION (
	NTCN_SN NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	NTCN_SJ VARCHAR2(30) NOT NULL,
	NTCN_CN VARCHAR2(300) NOT NULL,
	ORIGIN_PATH VARCHAR2(100),
	FNCT_CTGRY_TY NUMBER,
	NTCN_CREAT_DT DATE
);

COMMENT ON TABLE NOTIFICATION IS '알림';

COMMENT ON COLUMN NOTIFICATION.NTCN_SN IS '알림 순번';

COMMENT ON COLUMN NOTIFICATION.EMPL_NO IS '알림을 받는 사원 넘버';

COMMENT ON COLUMN NOTIFICATION.NTCN_SJ IS '알림 제목';

COMMENT ON COLUMN NOTIFICATION.NTCN_CN IS '알림 내용';

COMMENT ON COLUMN NOTIFICATION.ORIGIN_PATH IS '기능별 NO =? /board/detail?boardNo=1';

COMMENT ON COLUMN NOTIFICATION.FNCT_CTGRY_TY IS '기능 PK';

COMMENT ON COLUMN NOTIFICATION.NTCN_CREAT_DT IS '알림 생성 일시';

CREATE UNIQUE INDEX PK_NOTIFICATION
	ON NOTIFICATION (
		NTCN_SN ASC,
		EMPL_NO ASC
	);

ALTER TABLE NOTIFICATION
	ADD
		CONSTRAINT PK_NOTIFICATION
		PRIMARY KEY (
			NTCN_SN,
			EMPL_NO
		);

CREATE TABLE FOLDER (
	FOLDER_NO NUMBER NOT NULL,
	UPPER_FOLDER_NO NUMBER,
	FOLDER_NM VARCHAR2(100) NOT NULL,
	FOLDER_PATH VARCHAR2(500) NOT NULL,
	FOLDER_TY VARCHAR2(1) NOT NULL,
	DEPT_CODE VARCHAR2(2),
	FOLDER_CREAT_DT DATE NOT NULL,
	FOLDER_UPDT_DT DATE NOT NULL,
	FOLDER_DELETE_YN VARCHAR2(1),
	FOLDER_CREAT_EMPNO VARCHAR2(8)
);

COMMENT ON TABLE FOLDER IS '폴더';

COMMENT ON COLUMN FOLDER.FOLDER_NO IS '폴더 번호';

COMMENT ON COLUMN FOLDER.UPPER_FOLDER_NO IS '상위 폴더 번호';

COMMENT ON COLUMN FOLDER.FOLDER_NM IS '폴더 명';

COMMENT ON COLUMN FOLDER.FOLDER_PATH IS '폴더 경로';

COMMENT ON COLUMN FOLDER.FOLDER_TY IS '0사내 / 1부서/ 2 개인';

COMMENT ON COLUMN FOLDER.DEPT_CODE IS '폴더 유형이 부서인 경우 부서 사람만 가능';

COMMENT ON COLUMN FOLDER.FOLDER_CREAT_DT IS '폴더 생성 일시';

COMMENT ON COLUMN FOLDER.FOLDER_UPDT_DT IS '폴더 수정 일시';

COMMENT ON COLUMN FOLDER.FOLDER_DELETE_YN IS '폴더 삭제 여부';

COMMENT ON COLUMN FOLDER.FOLDER_CREAT_EMPNO IS '폴더 생성 사번';

CREATE UNIQUE INDEX PK_FOLDER
	ON FOLDER (
		FOLDER_NO ASC
	);

ALTER TABLE FOLDER
	ADD
		CONSTRAINT PK_FOLDER
		PRIMARY KEY (
			FOLDER_NO
		);

CREATE TABLE FOLDER_FILE (
	FOLDER_NO NUMBER NOT NULL,
	ATCH_FILE_NO NUMBER NOT NULL,
	FILE_DWLD_CO NUMBER,
	FILE_UPLOAD_EMPNO VARCHAR2(8)
);

COMMENT ON TABLE FOLDER_FILE IS '폴더 파일';

COMMENT ON COLUMN FOLDER_FILE.FOLDER_NO IS '폴더 번호';

COMMENT ON COLUMN FOLDER_FILE.ATCH_FILE_NO IS '첨부 파일 번호';

COMMENT ON COLUMN FOLDER_FILE.FILE_DWLD_CO IS '파일 다운로드 횟수';

COMMENT ON COLUMN FOLDER_FILE.FILE_UPLOAD_EMPNO IS '파일 업로드 사번';

CREATE UNIQUE INDEX PK_FOLDER_FILE
	ON FOLDER_FILE (
		FOLDER_NO ASC,
		ATCH_FILE_NO ASC
	);

ALTER TABLE FOLDER_FILE
	ADD
		CONSTRAINT PK_FOLDER_FILE
		PRIMARY KEY (
			FOLDER_NO,
			ATCH_FILE_NO
		);

CREATE TABLE COMMON_CODE_GROUP (
	CMMN_CODE_GROUP VARCHAR2(100) NOT NULL,
	CODE_GROUP_NM VARCHAR2(100) NOT NULL,
	CODE_GROUP_DC VARCHAR2(200) NOT NULL,
	USE_YN CHAR(1),
	CMMN_CODE_GROUP_SN NUMBER
);

COMMENT ON TABLE COMMON_CODE_GROUP IS '공통 코드 그룹';

COMMENT ON COLUMN COMMON_CODE_GROUP.CMMN_CODE_GROUP IS '공통 코드 그룹';

COMMENT ON COLUMN COMMON_CODE_GROUP.CODE_GROUP_NM IS '코드 그룹 명';

COMMENT ON COLUMN COMMON_CODE_GROUP.CODE_GROUP_DC IS '코드 그룹 설명';

COMMENT ON COLUMN COMMON_CODE_GROUP.USE_YN IS 'Y /N';

COMMENT ON COLUMN COMMON_CODE_GROUP.CMMN_CODE_GROUP_SN IS '공통 코드 그룹 순번';

CREATE UNIQUE INDEX PK_COMMON_CODE_GROUP
	ON COMMON_CODE_GROUP (
		CMMN_CODE_GROUP ASC
	);

ALTER TABLE COMMON_CODE_GROUP
	ADD
		CONSTRAINT PK_COMMON_CODE_GROUP
		PRIMARY KEY (
			CMMN_CODE_GROUP
		);

CREATE TABLE TASK_LINK (
	TASK_LINK_NO NUMBER NOT NULL,
	TASK_NO NUMBER NOT NULL,
	LINK_SN NUMBER NOT NULL,
	TRGT_TASK_NO NUMBER,
	TASK_LINK_TY VARCHAR2(2) NOT NULL
);

COMMENT ON TABLE TASK_LINK IS '과제 링크';

COMMENT ON COLUMN TASK_LINK.TASK_LINK_NO IS '과제 링크 번호';

COMMENT ON COLUMN TASK_LINK.TASK_NO IS '과제 번호';

COMMENT ON COLUMN TASK_LINK.LINK_SN IS '과제 하위에 과제 순번';

COMMENT ON COLUMN TASK_LINK.TRGT_TASK_NO IS '타겟 과제 넘버가 없는 경우 마지막 과제';

COMMENT ON COLUMN TASK_LINK.TASK_LINK_TY IS '확인 후 추가';

CREATE UNIQUE INDEX PK_TASK_LINK
	ON TASK_LINK (
		TASK_LINK_NO ASC
	);

ALTER TABLE TASK_LINK
	ADD
		CONSTRAINT PK_TASK_LINK
		PRIMARY KEY (
			TASK_LINK_NO
		);

CREATE TABLE PROJECT_CATEGORY (
	CTGRY_NO NUMBER NOT NULL,
	CTGRY_NM VARCHAR2(100) NOT NULL,
	CTGRY_CREAT_DATE VARCHAR2(8),
	CTGRY_UPDT_DATE VARCHAR2(8),
	CTGRY_USE_YN VARCHAR2(1)
);

COMMENT ON TABLE PROJECT_CATEGORY IS '프로젝트 카테고리';

COMMENT ON COLUMN PROJECT_CATEGORY.CTGRY_NO IS '카테고리 번호';

COMMENT ON COLUMN PROJECT_CATEGORY.CTGRY_NM IS '카테고리 명';

COMMENT ON COLUMN PROJECT_CATEGORY.CTGRY_CREAT_DATE IS '카테고리 생성 일자';

COMMENT ON COLUMN PROJECT_CATEGORY.CTGRY_UPDT_DATE IS '카테고리 수정 일자';

COMMENT ON COLUMN PROJECT_CATEGORY.CTGRY_USE_YN IS 'Y / N';

CREATE UNIQUE INDEX PK_PROJECT_CATEGORY
	ON PROJECT_CATEGORY (
		CTGRY_NO ASC
	);

ALTER TABLE PROJECT_CATEGORY
	ADD
		CONSTRAINT PK_PROJECT_CATEGORY
		PRIMARY KEY (
			CTGRY_NO
		);

CREATE TABLE TASK_ANSERT (
	TASK_NO NUMBER NOT NULL,
	TASK_ANSWER_SN NUMBER NOT NULL,
	ANSWER_CN VARCHAR2(2000) NOT NULL,
	ANSWER_CREAT_DT DATE,
	ANSWER_UPDT_DT DATE,
	ANSWER_WRITNG_EMPNO VARCHAR2(8) NOT NULL
);

COMMENT ON TABLE TASK_ANSERT IS '과제 댓글';

COMMENT ON COLUMN TASK_ANSERT.TASK_NO IS '과제 번호';

COMMENT ON COLUMN TASK_ANSERT.TASK_ANSWER_SN IS '과제 댓글 순번';

COMMENT ON COLUMN TASK_ANSERT.ANSWER_CN IS '댓글 내용';

COMMENT ON COLUMN TASK_ANSERT.ANSWER_CREAT_DT IS '댓글 생성 일시';

COMMENT ON COLUMN TASK_ANSERT.ANSWER_UPDT_DT IS '댓글 수정 일시';

COMMENT ON COLUMN TASK_ANSERT.ANSWER_WRITNG_EMPNO IS '댓글 작성 사번';

CREATE UNIQUE INDEX PK_TASK_ANSERT
	ON TASK_ANSERT (
		TASK_NO ASC,
		TASK_ANSWER_SN ASC
	);

ALTER TABLE TASK_ANSERT
	ADD
		CONSTRAINT PK_TASK_ANSERT
		PRIMARY KEY (
			TASK_NO,
			TASK_ANSWER_SN
		);

CREATE TABLE PRQUDO (
	PRQUDO_NO VARCHAR2(12) NOT NULL,
	PRQUDO_NM VARCHAR2(100) NOT NULL,
	CMPNY_NM VARCHAR2(300) NOT NULL,
	EMP_CO NUMBER NOT NULL,
	CHARGER_NM VARCHAR2(50) NOT NULL,
	CHARGER_CTTPC VARCHAR2(11) NOT NULL,
	CHARGER_EMAIL VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE PRQUDO IS '견적서';

COMMENT ON COLUMN PRQUDO.PRQUDO_NO IS '202503240001';

COMMENT ON COLUMN PRQUDO.PRQUDO_NM IS '견적서 이름';

COMMENT ON COLUMN PRQUDO.CMPNY_NM IS '회사명';

COMMENT ON COLUMN PRQUDO.EMP_CO IS '직원수';

COMMENT ON COLUMN PRQUDO.CHARGER_NM IS '담당자 이름';

COMMENT ON COLUMN PRQUDO.CHARGER_CTTPC IS '담당자 연락처';

COMMENT ON COLUMN PRQUDO.CHARGER_EMAIL IS '담당자 이메일';

CREATE UNIQUE INDEX PK_PRQUDO
	ON PRQUDO (
		PRQUDO_NO ASC
	);

ALTER TABLE PRQUDO
	ADD
		CONSTRAINT PK_PRQUDO
		PRIMARY KEY (
			PRQUDO_NO
		);

CREATE TABLE PAY_REQUEST (
	SETLE_NO NUMBER NOT NULL,
	SETLE_GOODS_NM VARCHAR2(1000),
	TOT_SETLE_AMOUNT NUMBER NOT NULL,
	SETLE_CARD_CMPNY VARCHAR2(100),
	ORDER_STTUS VARCHAR2(50),
	PAYMENT_NO VARCHAR2(100) NOT NULL,
	SETLE_REQUST_DT DATE,
	PRQUDO_NO VARCHAR2(12)
);

COMMENT ON TABLE PAY_REQUEST IS '결제 요청';

COMMENT ON COLUMN PAY_REQUEST.SETLE_NO IS '결제 번호';

COMMENT ON COLUMN PAY_REQUEST.SETLE_GOODS_NM IS '결제 상품 명';

COMMENT ON COLUMN PAY_REQUEST.TOT_SETLE_AMOUNT IS '총 결제 금액';

COMMENT ON COLUMN PAY_REQUEST.SETLE_CARD_CMPNY IS '결제 카드 회사';

COMMENT ON COLUMN PAY_REQUEST.ORDER_STTUS IS 'SUCCESS, FAIL';

COMMENT ON COLUMN PAY_REQUEST.PAYMENT_NO IS '페이먼츠 넘버';

COMMENT ON COLUMN PAY_REQUEST.SETLE_REQUST_DT IS '결제 요청 일시';

COMMENT ON COLUMN PAY_REQUEST.PRQUDO_NO IS '견적서 번호';

CREATE UNIQUE INDEX PK_PAY_REQUEST
	ON PAY_REQUEST (
		SETLE_NO ASC
	);

ALTER TABLE PAY_REQUEST
	ADD
		CONSTRAINT PK_PAY_REQUEST
		PRIMARY KEY (
			SETLE_NO
		);

CREATE TABLE PAY_CONFIRM (
	SETLE_COMPT_NO NUMBER NOT NULL,
	SETLE_STTUS VARCHAR2(50),
	SETLE_MSSAGE VARCHAR2(1000),
	SETLE_CONFM_DT DATE,
	SETLE_NO NUMBER
);

COMMENT ON TABLE PAY_CONFIRM IS '결제 완료';

COMMENT ON COLUMN PAY_CONFIRM.SETLE_COMPT_NO IS '결제 완료 번호';

COMMENT ON COLUMN PAY_CONFIRM.SETLE_STTUS IS '결제 상태';

COMMENT ON COLUMN PAY_CONFIRM.SETLE_MSSAGE IS '결제 메세지';

COMMENT ON COLUMN PAY_CONFIRM.SETLE_CONFM_DT IS '결제 승인 일시';

COMMENT ON COLUMN PAY_CONFIRM.SETLE_NO IS '결제 번호';

CREATE UNIQUE INDEX PK_PAY_CONFIRM
	ON PAY_CONFIRM (
		SETLE_COMPT_NO ASC
	);

ALTER TABLE PAY_CONFIRM
	ADD
		CONSTRAINT PK_PAY_CONFIRM
		PRIMARY KEY (
			SETLE_COMPT_NO
		);

CREATE TABLE SCHEDULE_LABEL_COLOR (
	LBL_COLOR_NO NUMBER NOT NULL,
	LBL_COLOR VARCHAR2(100) NOT NULL,
	LBL_COLOR_NM VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE SCHEDULE_LABEL_COLOR IS '일정 라벨 색상';

COMMENT ON COLUMN SCHEDULE_LABEL_COLOR.LBL_COLOR_NO IS '라벨 색상 넘버';

COMMENT ON COLUMN SCHEDULE_LABEL_COLOR.LBL_COLOR IS '라벨 색상';

COMMENT ON COLUMN SCHEDULE_LABEL_COLOR.LBL_COLOR_NM IS '라벨 색상 명';

CREATE UNIQUE INDEX PK_SCHEDULE_LABEL_COLOR
	ON SCHEDULE_LABEL_COLOR (
		LBL_COLOR_NO ASC
	);

ALTER TABLE SCHEDULE_LABEL_COLOR
	ADD
		CONSTRAINT PK_SCHEDULE_LABEL_COLOR
		PRIMARY KEY (
			LBL_COLOR_NO
		);

CREATE TABLE NOTIFICATION_SETTING (
	NTCN_NO NUMBER NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL,
	SKLL_CODE VARCHAR2(2) NOT NULL,
	NTCN_YN VARCHAR(1) NOT NULL
);

COMMENT ON TABLE NOTIFICATION_SETTING IS '알림 설정';

COMMENT ON COLUMN NOTIFICATION_SETTING.NTCN_NO IS '알림 번호';

COMMENT ON COLUMN NOTIFICATION_SETTING.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN NOTIFICATION_SETTING.SKLL_CODE IS '기능 코드';

COMMENT ON COLUMN NOTIFICATION_SETTING.NTCN_YN IS 'Y / N';

CREATE UNIQUE INDEX PK_NOTIFICATION_SETTING
	ON NOTIFICATION_SETTING (
		NTCN_NO ASC,
		EMPL_NO ASC
	);

ALTER TABLE NOTIFICATION_SETTING
	ADD
		CONSTRAINT PK_NOTIFICATION_SETTING
		PRIMARY KEY (
			NTCN_NO,
			EMPL_NO
		);

CREATE TABLE AUTH (
	AUTHORITY VARCHAR2(50) NOT NULL,
	EMPL_NO VARCHAR2(8) NOT NULL
);

COMMENT ON TABLE AUTH IS '권한';

COMMENT ON COLUMN AUTH.AUTHORITY IS 'ROLL_ADMIN / ROLL_MEMBER';

COMMENT ON COLUMN AUTH.EMPL_NO IS '사원 번호';

CREATE UNIQUE INDEX PK_AUTH
	ON AUTH (
		AUTHORITY ASC,
		EMPL_NO ASC
	);

ALTER TABLE AUTH
	ADD
		CONSTRAINT PK_AUTH
		PRIMARY KEY (
			AUTHORITY,
			EMPL_NO
		);

CREATE TABLE VACATION_ADJU (
	EMPL_NO VARCHAR2(8) NOT NULL,
	YRYC_MDAT_TY VARCHAR(1),
	YRYC_CO NUMBER,
	YRYC_MDAT_DATE VARCHAR2(8),
	YRYC_MDAT_PRVONSH VARCHAR2(1000)
);

COMMENT ON TABLE VACATION_ADJU IS '연차 조정';

COMMENT ON COLUMN VACATION_ADJU.EMPL_NO IS '사원 번호';

COMMENT ON COLUMN VACATION_ADJU.YRYC_MDAT_TY IS '추가, 수정';

COMMENT ON COLUMN VACATION_ADJU.YRYC_CO IS '연차 수';

COMMENT ON COLUMN VACATION_ADJU.YRYC_MDAT_DATE IS '연차 조정 일자';

COMMENT ON COLUMN VACATION_ADJU.YRYC_MDAT_PRVONSH IS '연차 조정 사유';

CREATE UNIQUE INDEX PK_VACATION_ADJU
	ON VACATION_ADJU (
		EMPL_NO ASC
	);

ALTER TABLE VACATION_ADJU
	ADD
		CONSTRAINT PK_VACATION_ADJU
		PRIMARY KEY (
			EMPL_NO
		);

ALTER TABLE SKILL_AUTH
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_SKILL_AUTH
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE COMMON_CODE
	ADD
		CONSTRAINT FK_COMMON_CODE_GROUP_TO_COMMON_CODE
		FOREIGN KEY (
			CMMN_CODE_GROUP
		)
		REFERENCES COMMON_CODE_GROUP (
			CMMN_CODE_GROUP
		);

ALTER TABLE ATTATCH_FILE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_ATTATCH_FILE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE DCLZ_TYPE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_DCLZ_TYPE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE VACATION
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_VACATION
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE ATRZ
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ
		FOREIGN KEY (
			DRAFTER_EMPNO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE ATRZ
	ADD
		CONSTRAINT FK_DOC_FORM_TO_ATRZ
		FOREIGN KEY (
			DOC_FORM_NO
		)
		REFERENCES DOC_FORM (
			DOC_FORM_NO
		);

ALTER TABLE ATRZ_LINE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_LINE
		FOREIGN KEY (
			SANCTNER_EMPNO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE ATRZ_LINE
	ADD
		CONSTRAINT FK_ATRZ_TO_ATRZ_LINE
		FOREIGN KEY (
			ATRZ_DOC_NO
		)
		REFERENCES ATRZ (
			ATRZ_DOC_NO
		);

ALTER TABLE VACTION_PLAN
	ADD
		CONSTRAINT FK_ATRZ_TO_VACTION_PLAN
		FOREIGN KEY (
			ATRZ_DOC_NO
		)
		REFERENCES ATRZ (
			ATRZ_DOC_NO
		);

ALTER TABLE ATRZ_LIKE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_LIKE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE ATRZ_EMP
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_ATRZ_EMP
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE ATRZ_EMP
	ADD
		CONSTRAINT FK_ATRZ_LIKE_TO_ATRZ_EMP
		FOREIGN KEY (
			ATRZ_LN_BKMK_NO
		)
		REFERENCES ATRZ_LIKE (
			ATRZ_LN_BKMK_NO
		);

ALTER TABLE SCHEDULE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_SCHEDULE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE SCHEDULE
	ADD
		CONSTRAINT FK_SCHEDULE_LABEL_COLOR_TO_SCHEDULE
		FOREIGN KEY (
			LBL_COLOR_NO
		)
		REFERENCES SCHEDULE_LABEL_COLOR (
			LBL_COLOR_NO
		);

ALTER TABLE SCHEDULE_AUTH_GROUP
	ADD
		CONSTRAINT FK_SCHEDULE_TO_SCHEDULE_AUTH_GROUP
		FOREIGN KEY (
			SCHDUL_NO
		)
		REFERENCES SCHEDULE (
			SCHDUL_NO
		);

ALTER TABLE SCHEDULE_AUTH_GROUP
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_SCHEDULE_AUTH_GROUP
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE SCHEDULE_TYPE
	ADD
		CONSTRAINT FK_SCHEDULE_TO_SCHEDULE_TYPE
		FOREIGN KEY (
			SCHDUL_NO
		)
		REFERENCES SCHEDULE (
			SCHDUL_NO
		);

ALTER TABLE MAIL
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_MAIL
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE MAIL
	ADD
		CONSTRAINT FK_MAIL_LABEL_TO_MAIL
		FOREIGN KEY (
			LBL_NO
		)
		REFERENCES MAIL_LABEL (
			LBL_NO
		);

ALTER TABLE MAIL_LABEL
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_MAIL_LABEL
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE MAIL_TEMPLATE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_MAIL_TEMPLATE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE PROJECT
	ADD
		CONSTRAINT FK_PROJECT_CATEGORY_TO_PROJECT
		FOREIGN KEY (
			CTGRY_NO
		)
		REFERENCES PROJECT_CATEGORY (
			CTGRY_NO
		);

ALTER TABLE PROJECT_EMP
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_PROJECT_EMP
		FOREIGN KEY (
			PRTCPNT_EMPNO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE PROJECT_EMP
	ADD
		CONSTRAINT FK_PROJECT_TO_PROJECT_EMP
		FOREIGN KEY (
			PRJCT_NO
		)
		REFERENCES PROJECT (
			PRJCT_NO
		);

ALTER TABLE PROJECT_EMP
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_PROJECT_EMP2
		FOREIGN KEY (
			EVL_MAN_EMPNO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE PROJECT_TASK
	ADD
		CONSTRAINT FK_PROJECT_TASK_TO_PROJECT_TASK
		FOREIGN KEY (
			UPPER_TASK_NO
		)
		REFERENCES PROJECT_TASK (
			TASK_NO
		);

ALTER TABLE PROJECT_TASK
	ADD
		CONSTRAINT FK_PROJECT_EMP_TO_PROJECT_TASK
		FOREIGN KEY (
			PRJCT_NO,
			CHARGER_EMPNO
		)
		REFERENCES PROJECT_EMP (
			PRJCT_NO,
			PRTCPNT_EMPNO
		);

ALTER TABLE BBS
	ADD
		CONSTRAINT FK_BBS_CTGRY_TO_BBS
		FOREIGN KEY (
			BBS_CTGRY_NO
		)
		REFERENCES BBS_CTGRY (
			BBS_CTGRY_NO
		);

ALTER TABLE BBS
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_BBS
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE BBS_ANSWER
	ADD
		CONSTRAINT FK_BBS_TO_BBS_ANSWER
		FOREIGN KEY (
			BBS_SN,
			BBS_CTGRY_NO
		)
		REFERENCES BBS (
			BBS_SN,
			BBS_CTGRY_NO
		);

ALTER TABLE BBS_ANSWER
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_BBS_ANSWER
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE BBS_LIKE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_BBS_LIKE
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE BBS_LIKE
	ADD
		CONSTRAINT FK_BBS_TO_BBS_LIKE
		FOREIGN KEY (
			BBS_SN,
			BBS_CTGRY_NO
		)
		REFERENCES BBS (
			BBS_SN,
			BBS_CTGRY_NO
		);

ALTER TABLE CHAT_EMP
	ADD
		CONSTRAINT FK_CHAT_ROOM_TO_CHAT_EMP
		FOREIGN KEY (
			CHTT_ROOM_NO
		)
		REFERENCES CHAT_ROOM (
			CHTT_ROOM_NO
		);

ALTER TABLE CHAT_EMP
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_CHAT_EMP
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE CHAT_MESSAGE
	ADD
		CONSTRAINT FK_CHAT_EMP_TO_CHAT_MESSAGE
		FOREIGN KEY (
			CHTT_ROOM_NO,
			MSSAGE_WRITNG_EMPNO
		)
		REFERENCES CHAT_EMP (
			CHTT_ROOM_NO,
			EMPL_NO
		);

ALTER TABLE NOTIFICATION
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_NOTIFICATION
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE FOLDER_FILE
	ADD
		CONSTRAINT FK_FOLDER_TO_FOLDER_FILE
		FOREIGN KEY (
			FOLDER_NO
		)
		REFERENCES FOLDER (
			FOLDER_NO
		);

ALTER TABLE TASK_LINK
	ADD
		CONSTRAINT FK_PROJECT_TASK_TO_TASK_LINK
		FOREIGN KEY (
			TASK_NO
		)
		REFERENCES PROJECT_TASK (
			TASK_NO
		);

ALTER TABLE TASK_ANSERT
	ADD
		CONSTRAINT FK_PROJECT_TASK_TO_TASK_ANSERT
		FOREIGN KEY (
			TASK_NO
		)
		REFERENCES PROJECT_TASK (
			TASK_NO
		);

ALTER TABLE TASK_ANSERT
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_TASK_ANSERT
		FOREIGN KEY (
			ANSWER_WRITNG_EMPNO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE PAY_REQUEST
	ADD
		CONSTRAINT FK_PRQUDO_TO_PAY_REQUEST
		FOREIGN KEY (
			PRQUDO_NO
		)
		REFERENCES PRQUDO (
			PRQUDO_NO
		);

ALTER TABLE PAY_CONFIRM
	ADD
		CONSTRAINT FK_PAY_REQUEST_TO_PAY_CONFIRM
		FOREIGN KEY (
			SETLE_NO
		)
		REFERENCES PAY_REQUEST (
			SETLE_NO
		);

ALTER TABLE NOTIFICATION_SETTING
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_NOTIFICATION_SETTING
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE AUTH
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_AUTH
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);

ALTER TABLE VACATION_ADJU
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_VACATION_ADJU
		FOREIGN KEY (
			EMPL_NO
		)
		REFERENCES EMPLOYEE (
			EMPL_NO
		);