
CREATE OR REPLACE FUNCTION create_doc_no(
    DOC_HEAD IN VARCHAR2)
    RETURN VARCHAR2
IS 
    L_DOC_NO VARCHAR2(50);
BEGIN
    SELECT DOC_HEAD || '_' || TO_CHAR(SYSDATE, 'YYYY') || '_' || LPAD((SELECT COUNT(*) + 1 FROM ATRZ WHERE ATRZ_DOC_NO LIKE DOC_HEAD), 5, 0) into L_DOC_NO
    FROM DUAL;
    
    RETURN L_DOC_NO;
END;
/




SELECT 
    'A' || '_' || TO_CHAR(SYSDATE, 'YYYY') || '_' || LPAD((SELECT COUNT(*) + 1 FROM ATRZ WHERE ATRZ_DOC_NO LIKE 'A'), 5, 0)
FROM DUAL;

SELECT COUNT(*) + 1
FROM ATRZ
WHERE ATRZ_DOC_NO LIKE 'A';

SELECT create_doc_no('C')
FROM DUAL;

-- A_202500001




SELECT EMP.EMPL_NO, DCLZ.DCLZ_NO, DCLZ.DCLZ_CODE, DCLZ.DCLZ_BEGIN_DT, EMP.DEPT_CODE
FROM DCLZ_TYPE DCLZ
LEFT JOIN EMPLOYEE EMP ON (DCLZ.EMPL_NO = EMP.EMPL_NO)
WHERE DCLZ.DCLZ_BEGIN_DT LIKE '2025%'
   OR DCLZ.DCLZ_CODE = 01 -- 지각
   OR DCLZ.DCLZ_CODE = 03; -- 조퇴

SELECT CR.CHTT_ROOM_NO, CHTT_ROOM_TY, 
       CHTT_ROOM_NM,
                CR.READ_COUNT,
               
               NVL(M.MSSAGE_CREAT_DT, CR.CHTT_CREAT_DT) AS CHTT_CREAT_DT,
               M.MSSAGE_CN as LAST_MSG,
               CE.EMPL_NO,
               M.MSSAGE_TY,
               (SELECT PROFL_PHOTO_URL FROM EMPLOYEE WHERE EMPL_NO = CE.EMPL_NO) AS PROFILE_URL
        FROM (SELECT CER.*, CRE.LAST_MSSAGE_NO, CRE.CHTT_CREAT_DT, CRE.CHTT_ROOM_NM, CRE.CHTT_ROOM_TY,
                NVL(CRE.LAST_MSSAGE_NO - CER.LAST_CNFIRM_NO, 0) as READ_COUNT
                FROM CHAT_EMP CER
                LEFT JOIN CHAT_ROOM CRE ON (CER.CHTT_ROOM_NO = CRE.CHTT_ROOM_NO)
                WHERE EMPL_NO = '20250001') CR
        LEFT JOIN CHAT_EMP CE ON(CE.CHTT_ROOM_NO = CR.CHTT_ROOM_NO AND CE.EMPL_NO != '20250001')
        LEFT JOIN CHAT_MESSAGE M ON (M.MSSAGE_SN = CR.LAST_MSSAGE_NO AND M.CHTT_ROOM_NO = CR.CHTT_ROOM_NO)
        ORDER BY CHTT_CREAT_DT DESC;
                
-- 내가 들어간 채팅방 번호를 가져온다
SELECT CER.*, CRE.LAST_MSSAGE_NO, CRE.CHTT_CREAT_DT
FROM CHAT_EMP CER
LEFT JOIN CHAT_ROOM CRE ON (CER.CHTT_ROOM_NO = CRE.CHTT_ROOM_NO)
WHERE EMPL_NO = '20250001';


SELECT CR.CHTT_ROOM_NO, CHTT_ROOM_TY, 
       CHTT_ROOM_NM,
        NVL(CR.LAST_MSSAGE_NO - CE.LAST_CNFIRM_NO, 0) as READ_COUNT,
        NVL(M.MSSAGE_CREAT_DT, CR.CHTT_CREAT_DT) AS CHTT_CREAT_DT,
        M.MSSAGE_CN as LAST_MSG,
        CE.EMPL_NO,
        M.MSSAGE_TY,
        (SELECT EMPL_NM FROM EMPLOYEE WHERE EMPL_NO = CE.EMPL_NO) AS PROFILE_URL,
        (SELECT PROFL_PHOTO_URL FROM EMPLOYEE WHERE EMPL_NO = CE.EMPL_NO) AS PROFILE_URL
FROM (SELECT B.CHTT_ROOM_NO, B.LAST_MSSAGE_NO, B.CHTT_CREAT_DT, B.CHTT_ROOM_NM, B.CHTT_ROOM_TY
      FROM CHAT_EMP A
      LEFT JOIN CHAT_ROOM B ON (A.CHTT_ROOM_NO = B.CHTT_ROOM_NO)
      WHERE EMPL_NO = '20250001') CR
LEFT JOIN CHAT_EMP CE ON(CE.CHTT_ROOM_NO = CR.CHTT_ROOM_NO AND CE.EMPL_NO != '20250001') --  
LEFT JOIN CHAT_MESSAGE M ON (M.MSSAGE_SN = CR.LAST_MSSAGE_NO AND M.CHTT_ROOM_NO = CR.CHTT_ROOM_NO)
ORDER BY CHTT_CREAT_DT DESC;



SELECT CR.CHTT_ROOM_NO, CHTT_ROOM_TY, 
       CHTT_ROOM_NM,
        NVL(CR.LAST_MSSAGE_NO - CE.LAST_CNFIRM_NO, 0) as READ_COUNT,
        NVL(M.MSSAGE_CREAT_DT, CR.CHTT_CREAT_DT) AS CHTT_CREAT_DT,
        M.MSSAGE_CN as LAST_MSG,
        CE.EMPL_NO,
        M.MSSAGE_TY,
        E.EMPL_NM, E.PROFL_PHOTO_URL
FROM (SELECT B.CHTT_ROOM_NO, B.LAST_MSSAGE_NO, B.CHTT_CREAT_DT, B.CHTT_ROOM_NM, B.CHTT_ROOM_TY
      FROM CHAT_EMP A
      LEFT JOIN CHAT_ROOM B ON (A.CHTT_ROOM_NO = B.CHTT_ROOM_NO)
      WHERE EMPL_NO = '20250001') CR
LEFT JOIN CHAT_EMP CE ON(CE.CHTT_ROOM_NO = CR.CHTT_ROOM_NO AND CE.EMPL_NO != '20250001') --  
LEFT JOIN EMPLOYEE E ON (E.EMPL_NO = CE.EMPL_NO)
LEFT JOIN CHAT_MESSAGE M ON (M.MSSAGE_SN = CR.LAST_MSSAGE_NO AND M.CHTT_ROOM_NO = CR.CHTT_ROOM_NO)
ORDER BY CHTT_CREAT_DT DESC;


SELECT *
FROM CHAT_EMP;




SELECT A.CHTT_ROOM_NO, A.EMPL_NO AS E1, B.EMPL_NO AS E2
FROM CHAT_EMP A
LEFT JOIN CHAT_EMP B 
ON A.CHTT_ROOM_NO = B.CHTT_ROOM_NO 
AND A.EMPL_NO != B.EMPL_NO
WHERE A.EMPL_NO = '20250001'
UNION ALL
SELECT 0 AS CHTT_ROOM_NO, '20250003' AS E1, '20250000' AS E2 FROM DUAL;


CREATE SEQUENCE SEQ_NOTIFICATION;

INSERT INTO NOTIFICATION (NTCN_SN, EMPL_NO, NTCN_SJ, NTCN_CN, ORIGIN_PATH, SKILL_CODE, NTCN_CREAT_DT, NTCN_READ_YN)
VALUES(SEQ_NOTIFICATION.NEXTVAL, '20250001', '[게시판 알림] 알림 제목입니다', '[게시판 알림] 이 알림은 미국에서 시작해서', '/chat/list', '01', SYSDATE, 'N');
commit;


        SELECT  ROW_NUMBER() OVER(ORDER BY ntcn_sn) RNUM
             , COUNT(1) OVER() AS total_count
             , ntcn_sn
             , empl_no
             , ntcn_sj
             , ntcn_cn
             , origin_path
             , skill_code
             , ntcn_creat_dt
        FROM NOTIFICATION
        WHERE EMPL_NO = '20250001'
        ORDER BY ntcn_creat_dt DESC
        OFFSET (1 - 1) * 10 ROWS
        FETCH FIRST 10 ROWS ONLY;

        SELECT ntcn_sn
             , empl_no
             , ntcn_sj
             , ntcn_cn
             , origin_path
             , skill_code
             , ntcn_creat_dt
        FROM NOTIFICATION
        WHERE empl_no = '20250001'
          AND ntcn_read_yn = 'N';